import React, { useEffect, useState } from 'react'
import { FileText, Loader2, Plug, Sparkles } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import { translate } from '@/i18n/i18n'
import type { AgentReachableItem, AgentView } from '../../../../shared/buildex-brain-types'
import { EMPTY_AGENT_VIEW } from '../../../../shared/buildex-brain-types'

// What the agent sees when a chat starts here.
//
// The split is the point. Operators assume that everything BuildEx has wired up
// is sitting in the conversation, and it is not: project memory is read in full,
// while skills, connectors and documents are only NAMED — the agent opens them
// if it decides it needs them. Showing the two halves apart is the difference
// between trusting the system and guessing at it.
//
// Rendered from files on disk with no model involved. Memory files are shown
// verbatim and their `@` lines are shown as written — this screen says nothing
// about what an import contains, because it never reads one. A connected app is
// its name and its host or program; no header, env value or argument is ever
// carried here, so there is no value left to mask.

const KIND_ICON = { skill: Sparkles, mcp: Plug, document: FileText } as const

const KIND_LABEL: Record<AgentReachableItem['kind'], string> = {
  skill: 'Skills',
  mcp: 'Connected apps',
  document: 'Documents'
}

export default function BrainAgentView({
  repoPath,
  open,
  onOpenChange
}: {
  repoPath: string
  open: boolean
  onOpenChange: (next: boolean) => void
}): React.JSX.Element {
  const [view, setView] = useState<AgentView>(EMPTY_AGENT_VIEW)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!open) {
      return
    }
    let cancelled = false
    setLoading(true)
    void window.api.buildexBrain
      .agentView({ repoPath })
      .then((next) => {
        if (!cancelled) {
          setView(next)
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false)
        }
      })
    return () => {
      cancelled = true
    }
  }, [open, repoPath])

  const groups = (['skill', 'mcp', 'document'] as const)
    .map((kind) => ({ kind, items: view.reachable.filter((item) => item.kind === kind) }))
    .filter((group) => group.items.length > 0)

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex max-h-[80vh] w-[46rem] max-w-[92vw] flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle>
            {translate('buildex.brain.agentView.title', 'What the agent sees')}
          </DialogTitle>
          <DialogDescription>
            {translate(
              'buildex.brain.agentView.subtitle',
              'Everything below is read from this repo. Nothing here is generated by a model.'
            )}
          </DialogDescription>
        </DialogHeader>

        {loading ? (
          <div className="flex flex-1 items-center justify-center py-10">
            <Loader2 size={16} className="animate-spin text-muted-foreground" />
          </div>
        ) : (
          <div className="scrollbar-sleek min-h-0 flex-1 space-y-6 overflow-y-auto pr-1">
            <section>
              <h3 className="text-[12px] font-semibold">
                {translate('buildex.brain.agentView.loaded', 'Loaded before you type')}
              </h3>
              <p className="mt-1 text-[11px] text-muted-foreground">
                {translate(
                  'buildex.brain.agentView.loadedHint',
                  'Read in full at the start of every new chat — {{value0}} characters in the files below. An @ line is listed exactly as written; select one to reveal it in your file manager.',
                  { value0: view.loadedCharacters.toLocaleString() }
                )}
              </p>
              <div className="mt-3 space-y-3">
                {view.alwaysLoaded.length === 0 ? (
                  <p className="text-[12px] text-muted-foreground">
                    {translate(
                      'buildex.brain.agentView.noneLoaded',
                      'Nothing yet — this repo has no project instructions.'
                    )}
                  </p>
                ) : (
                  view.alwaysLoaded.map((file) => (
                    // Imports sit outside the disclosure on purpose: what a
                    // memory file pulls in is half the answer, and it should not
                    // need reading the whole file to find.
                    <div key={file.path} className="rounded-md border border-border">
                      <div className="px-3 py-2">
                        <p className="font-mono text-[12px]">{file.path}</p>
                        {file.imports.length > 0 ? (
                          <>
                            <p className="mt-1.5 text-[11px] font-medium text-muted-foreground">
                              {translate('buildex.brain.agentView.imports', 'Imports')}
                            </p>
                            <ul className="mt-0.5 space-y-0.5">
                              {file.imports.map((entry, index) => {
                                const openTarget = entry.absolutePath
                                return (
                                  <li
                                    key={`${entry.target}:${index}`}
                                    className="font-mono text-[11px] text-muted-foreground"
                                  >
                                    {openTarget ? (
                                      <button
                                        type="button"
                                        onClick={() => void window.api.shell.openPath(openTarget)}
                                        className="underline underline-offset-2 hover:text-foreground"
                                      >
                                        @{entry.target}
                                      </button>
                                    ) : (
                                      <span>@{entry.target}</span>
                                    )}
                                  </li>
                                )
                              })}
                            </ul>
                          </>
                        ) : null}
                      </div>
                      {file.body ? (
                        <details className="border-t border-border">
                          <summary className="cursor-pointer px-3 py-2 text-[11px] text-muted-foreground">
                            {translate('buildex.brain.agentView.contents', 'Contents')}
                          </summary>
                          <pre className="scrollbar-sleek max-h-72 overflow-auto border-t border-border px-3 py-2 text-[11px] leading-relaxed whitespace-pre-wrap text-muted-foreground">
                            {file.body}
                          </pre>
                        </details>
                      ) : null}
                    </div>
                  ))
                )}
              </div>
            </section>

            <section>
              <h3 className="text-[12px] font-semibold">
                {translate('buildex.brain.agentView.reachable', 'Named, and opened only if needed')}
              </h3>
              <p className="mt-1 text-[11px] text-muted-foreground">
                {translate(
                  'buildex.brain.agentView.reachableHint',
                  'The agent knows these exist and what each one is for. It reads them when the work calls for it, not before.'
                )}
              </p>
              <div className="mt-3 space-y-4">
                {groups.map((group) => {
                  const Icon = KIND_ICON[group.kind]
                  return (
                    <div key={group.kind}>
                      <p className="flex items-center gap-1.5 text-[11px] font-medium text-muted-foreground">
                        <Icon size={11} />
                        {translate(
                          `buildex.brain.agentView.kind.${group.kind}`,
                          KIND_LABEL[group.kind]
                        )}
                        <span className="tabular-nums">({group.items.length})</span>
                      </p>
                      <ul className="mt-1.5 space-y-1">
                        {group.items.map((item) => (
                          <li key={`${item.kind}:${item.name}`} className="text-[12px]">
                            <span className="font-mono">{item.name}</span>
                            {item.detail ? (
                              <span className="ml-2 text-[11px] text-muted-foreground">
                                {item.detail}
                              </span>
                            ) : null}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )
                })}
                {groups.length === 0 ? (
                  <p className="text-[12px] text-muted-foreground">
                    {translate(
                      'buildex.brain.agentView.noneReachable',
                      'Nothing yet — no documents, skills or connected apps.'
                    )}
                  </p>
                ) : null}
              </div>
            </section>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
