// Bundle the daemon into a single CJS file for the packaged app (B2b). The Electron main process
// requires build/daemon.cjs and calls startPackagedDaemon() in-process - there is no tsx / no repo in
// a shipped app, so the whole daemon (its only runtime dep is @modelcontextprotocol/sdk via
// @buildex/connectors; everything else is Node built-ins) is compiled ahead of time.
//
// Release-machine step, NOT run in CI (like electron-builder). Run: npm run -w @buildex/client build:daemon
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const CLIENT = join(dirname(fileURLToPath(import.meta.url)), "..");

await build({
  entryPoints: [join(CLIENT, "src", "daemon-entry.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  outfile: join(CLIENT, "build", "daemon.cjs"),
  // Electron is provided by the host process at runtime; never bundle it. Node built-ins are external
  // automatically under platform:node. Everything else (the SDK) is bundled in.
  external: ["electron"],
  logLevel: "info",
  banner: {
    // esbuild's CJS output uses __dirname (which daemon-entry relies on to find the pack/web/gate-hook)
    // - under CJS that is the real output-file dir, exactly what we want. No shim needed.
    js: "// Generated by build-daemon.mjs - do not edit. Source: apps/client/src/daemon-entry.ts",
  },
});

console.log("✓ bundled apps/client/build/daemon.cjs");
