// Regenerate the agent-facing config on every sync (on every sync). For Tier-1 Claude
// Code this is the native discovery surface - no wrapper protocol: an assembled CLAUDE.md,
// linked .claude/skills/* with precedence private>team>core (the one part ported from the
// prototype), and a .claude/settings.json carrying the allow/ask/deny policy preset plus a
// PreToolUse hook that routes ask-tier tools to the daemon's gate. Deterministic - safe to rerun.
//
// Skill linking is platform-aware: POSIX uses directory symlinks; Windows uses junctions (which,
// unlike dir symlinks, need no Developer Mode / elevation - the operator is non-technical), and
// falls back to a plain copy when even a junction can't be made (e.g. workspace and repos on
// different volumes). Because a junction/copy isn't reported as a symlink and a copy's bytes live
// inside the workspace, provenance can't be inferred from the link target - so we also emit a
// deterministic skill-origins.json manifest that readSkill consults (zero-LLM trust surface).
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync, rmdirSync, unlinkSync, symlinkSync, statSync, realpathSync, cpSync } from "node:fs";
import { join } from "node:path";
import type { PolicyPreset } from "../gate/policy.js";
import { GATE_HOOK_TIMEOUT_SECS } from "../gate/approval.js";

/** How a resolved skill dir is materialized into .claude/skills. */
export type LinkStrategy = "symlink" | "junction" | "copy";

/** POSIX gets dir symlinks; Windows gets junctions (no elevation needed, copy-fallback on failure). */
export function defaultLinkStrategy(platform: NodeJS.Platform): LinkStrategy {
  return platform === "win32" ? "junction" : "symlink";
}

/** A workspace repo, in precedence order (index 0 = lowest = core). */
export interface Root {
  name: string;
  dir: string;
}

export interface GenerateOpts {
  workspace: string;
  /** Roots in ascending precedence: [core, team, private]. Later roots override earlier ones. */
  roots: Root[];
  preset: PolicyPreset;
  /** The command the PreToolUse hook runs to consult the daemon's gate. Omit to write permissions
   *  only (the agent's native allow/ask/deny) with no custom hook - used by the local demo. */
  gateCommand?: string;
  /** The PreToolUse hook's timeout in seconds (only used when gateCommand is set). Defaults to
   *  GATE_HOOK_TIMEOUT_SECS - long enough for a human approval, and above the card TTL so a stalled
   *  card auto-denies cleanly before Claude's timeout (which would otherwise let the tool proceed). */
  gateTimeoutSecs?: number;
  /** How to materialize skill links. Defaults per-platform (junction on Windows, symlink elsewhere);
   *  set explicitly for tests or to force a copy where linking is unavailable. */
  linkStrategy?: LinkStrategy;
}

export function generateAgentConfig(opts: GenerateOpts): void {
  writeAssembledRules(opts);
  linkSkills(opts);
  writeSettings(opts);
}

/** Concatenate each root's CLAUDE.md (core → team → private) into the workspace CLAUDE.md. */
function writeAssembledRules(opts: GenerateOpts): void {
  const parts: string[] = [
    "<!-- Generated by buildex on sync. Do not edit - edit the source rules in core/team/private. -->",
  ];
  for (const root of opts.roots) {
    const src = join(root.dir, "CLAUDE.md");
    if (existsSync(src)) {
      parts.push(`\n# ${root.name} rules\n`, readFileSync(src, "utf8").trimEnd());
    }
  }
  writeFileSync(join(opts.workspace, "CLAUDE.md"), parts.join("\n") + "\n");
}

/** Link skills into .claude/skills, later roots (private>team>core) overriding by name, and emit
 *  the skill-origins manifest so provenance survives junctions/copies where the link target can't
 *  be read back (Windows). */
function linkSkills(opts: GenerateOpts): void {
  const dest = join(opts.workspace, ".claude", "skills");
  rmSync(dest, { recursive: true, force: true });
  mkdirSync(dest, { recursive: true });
  const strategy = opts.linkStrategy ?? defaultLinkStrategy(process.platform);

  // Resolve name → { source dir, winning repo }, applying precedence (roots given low→high, last wins).
  const resolved = new Map<string, { src: string; root: string }>();
  for (const root of opts.roots) {
    const skillsDir = join(root.dir, "skills");
    if (!existsSync(skillsDir)) continue;
    for (const name of readdirSync(skillsDir).sort()) {
      const src = join(skillsDir, name);
      if (statSync(src).isDirectory()) resolved.set(name, { src, root: root.name });
    }
  }

  const origins: Record<string, string> = {};
  for (const name of [...resolved.keys()].sort()) {
    const { src, root } = resolved.get(name)!;
    linkOne(src, join(dest, name), strategy);
    origins[name] = root;
  }
  // Sibling of skills/ (not inside it, so it's never scanned as a verb); overwritten each sync.
  writeFileSync(join(opts.workspace, ".claude", "skill-origins.json"), JSON.stringify(origins, null, 2) + "\n");
}

/** Materialize one resolved skill dir at `dest` per strategy. Junctions/copies need no elevation;
 *  a junction that can't be made (e.g. cross-volume) falls back to a plain recursive copy. */
function linkOne(src: string, dest: string, strategy: LinkStrategy): void {
  if (strategy === "copy") {
    clearDest(dest);
    return void cpSync(src, dest, { recursive: true });
  }
  if (strategy === "junction") {
    try {
      symlinkSync(src, dest, "junction");
    } catch {
      // dest already exists - a stale junction from an interrupted or concurrent earlier run. If it
      // already points at src, nothing to do; otherwise clear the LINK (never followed into its target,
      // which is the real skill source) and recreate, falling back to a copy. This makes re-linking
      // idempotent on Windows, where re-creating over an existing junction otherwise throws
      // "src and dest cannot be the same".
      try {
        if (realpathSync(dest) === realpathSync(src)) return;
      } catch {
        /* dest unreadable - fall through to clear + recreate */
      }
      clearDest(dest);
      try {
        symlinkSync(src, dest, "junction");
      } catch {
        cpSync(src, dest, { recursive: true });
      }
    }
    return;
  }
  try {
    symlinkSync(src, dest); // POSIX directory symlink
  } catch {
    clearDest(dest);
    symlinkSync(src, dest);
  }
}

/** Remove whatever is at `dest` (a junction, a symlink, or a real copied dir) as the ENTRY itself -
 *  never recursing through a junction into its target (that target is the real skill source we must not
 *  touch). rmdir removes a junction link or an empty dir; unlink removes a file/symlink; only a real,
 *  non-empty copied dir needs a recursive remove (no junction to follow, so it is safe). */
function clearDest(dest: string): void {
  try {
    rmdirSync(dest); // junction link, dir symlink, or empty dir - removed without following
    return;
  } catch {
    /* not a junction / not an empty dir */
  }
  try {
    unlinkSync(dest); // file or file symlink
    return;
  } catch {
    /* not a file */
  }
  try {
    rmSync(dest, { recursive: true, force: true }); // a real (copied) directory's contents
  } catch {
    /* already gone */
  }
}

/** Write .claude/settings.json: the policy preset as permissions + the PreToolUse gate hook. */
function writeSettings(opts: GenerateOpts): void {
  const dir = join(opts.workspace, ".claude");
  mkdirSync(dir, { recursive: true });
  const settings: {
    permissions: { allow: string[]; ask: string[]; deny: string[] };
    hooks?: { PreToolUse: { matcher: string; hooks: { type: string; command: string; timeout: number }[] }[] };
  } = {
    permissions: {
      allow: opts.preset.allow,
      ask: opts.preset.ask,
      deny: opts.preset.deny,
    },
  };
  if (opts.gateCommand) {
    // matcher "*" fires the hook before EVERY tool call (verified against Claude Code 2.1.x); the
    // timeout must exceed the card TTL so a stalled approval auto-denies cleanly rather than timing
    // the hook out (a hook timeout is non-blocking and would let the tool proceed ungated).
    const timeout = opts.gateTimeoutSecs ?? GATE_HOOK_TIMEOUT_SECS;
    settings.hooks = {
      PreToolUse: [{ matcher: "*", hooks: [{ type: "command", command: opts.gateCommand, timeout }] }],
    };
  }
  writeFileSync(join(dir, "settings.json"), JSON.stringify(settings, null, 2) + "\n");
}
