import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type { BrainScan } from '../../shared/buildex-brain-types'

// Auto-feeds the company brain to the coding agent.
//
// Why this mechanism: Claude Code already reads CLAUDE.md at session start and
// follows `@path` imports. Writing a generated context file and importing it
// means the agent picks up company context with no new runtime, no injection
// hook, and no per-agent integration — and because both files are in the repo,
// what the agent was told is reviewable in a diff like everything else.

export const CONTEXT_RELATIVE_PATH = '.buildex/company-context.md'
const IMPORT_LINE = `@${CONTEXT_RELATIVE_PATH}`
const BEGIN_MARKER = '<!-- buildex:company-context:begin -->'
const END_MARKER = '<!-- buildex:company-context:end -->'

/**
 * Render the agent-facing context. Deterministic: identical scan in, identical
 * bytes out, so re-syncing an unchanged brain produces no diff.
 */
export function renderCompanyContext(scan: BrainScan): string {
  const lines: string[] = [
    '# Company context',
    '',
    'Generated by BuildEx from this repo. Do not edit — regenerate from the',
    'Company Brain panel. Every entry below is a real file in this repository.',
    ''
  ]

  const byFolder = new Map<string, string[]>()
  for (const doc of scan.documents) {
    const bucket = byFolder.get(doc.folder) ?? []
    bucket.push(doc.name)
    byFolder.set(doc.folder, bucket)
  }

  lines.push(`## Documents (${scan.documents.length})`, '')
  for (const folder of [...byFolder.keys()].sort((a, b) => a.localeCompare(b))) {
    const names = (byFolder.get(folder) ?? []).slice().sort((a, b) => a.localeCompare(b))
    lines.push(`- **${folder === '' ? 'root' : folder}** — ${names.join(', ')}`)
  }
  lines.push('')

  // Why: the most-linked documents are the ones the company actually organises
  // around. Surfacing them tells the agent where to look first.
  const hubs = scan.documents
    .map((doc) => ({
      name: doc.name,
      id: doc.id,
      degree: doc.linksTo.length + doc.linkedFrom.length
    }))
    .filter((entry) => entry.degree > 0)
    .sort((a, b) => b.degree - a.degree || a.id.localeCompare(b.id))
    .slice(0, 10)

  if (hubs.length > 0) {
    lines.push('## Most connected', '')
    for (const hub of hubs) {
      lines.push(`- \`${hub.id}\` (${hub.degree} ${hub.degree === 1 ? 'link' : 'links'})`)
    }
    lines.push('')
  }

  const unsaved = scan.documents.filter((doc) => doc.changed).map((doc) => doc.id)
  if (unsaved.length > 0) {
    lines.push('## Uncommitted right now', '')
    for (const id of unsaved) {
      lines.push(`- \`${id}\``)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function withImportBlock(existing: string): string {
  const block = `${BEGIN_MARKER}\n${IMPORT_LINE}\n${END_MARKER}`
  const beginIndex = existing.indexOf(BEGIN_MARKER)
  const endIndex = existing.indexOf(END_MARKER)
  if (beginIndex !== -1 && endIndex > beginIndex) {
    // Why: replace only between the markers so an operator's own CLAUDE.md
    // content around them is never touched.
    return existing.slice(0, beginIndex) + block + existing.slice(endIndex + END_MARKER.length)
  }
  const separator = existing.trim() ? `${existing.replace(/\s*$/, '')}\n\n` : ''
  return `${separator}${block}\n`
}

export type ContextSyncResult = {
  contextPath: string
  claudeMdPath: string
  contextChanged: boolean
  claudeMdChanged: boolean
}

/**
 * Write the context file and ensure CLAUDE.md imports it.
 *
 * Idempotent for a given scan, and convergent across scans: creating CLAUDE.md
 * adds a document to the brain, so the next scan legitimately differs and a
 * second sync settles it. The generated context itself lives under `.buildex/`,
 * which the scanner skips as a dot-directory, so it never feeds back into
 * itself.
 */
export function syncCompanyContext(repoPath: string, scan: BrainScan): ContextSyncResult {
  const contextAbsolute = path.join(repoPath, CONTEXT_RELATIVE_PATH)
  const claudeMdAbsolute = path.join(repoPath, 'CLAUDE.md')

  const nextContext = renderCompanyContext(scan)
  const currentContext = existsSync(contextAbsolute) ? readFileSync(contextAbsolute, 'utf8') : null
  const contextChanged = currentContext !== nextContext
  if (contextChanged) {
    mkdirSync(path.dirname(contextAbsolute), { recursive: true })
    writeFileSync(contextAbsolute, nextContext, 'utf8')
  }

  const currentClaudeMd = existsSync(claudeMdAbsolute) ? readFileSync(claudeMdAbsolute, 'utf8') : ''
  const nextClaudeMd = withImportBlock(currentClaudeMd)
  const claudeMdChanged = currentClaudeMd !== nextClaudeMd
  if (claudeMdChanged) {
    writeFileSync(claudeMdAbsolute, nextClaudeMd, 'utf8')
  }

  return {
    contextPath: CONTEXT_RELATIVE_PATH,
    claudeMdPath: 'CLAUDE.md',
    contextChanged,
    claudeMdChanged
  }
}
